In [22]:
!pip3 install torch

In [23]:
SEPARATOR = "###############"

def sep(title=None):
    print(SEPARATOR, title or '', SEPARATOR, sep='')

In [24]:
import torch

z = torch.zeros(2)
print(z)

sep()

x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
x_diag = torch.diag(x)
print(x_diag)

sep("diagflat")

y = torch.randn(2, 2)
y_diagflat = torch.diagflat(y, 0)
print(y)
print(y_diagflat)


tensor([0., 0.])
##############################
tensor([ 1,  6, 11, 16])
###############diagflat###############
tensor([[1.2603, 0.0080],
        [1.6935, 0.0103]])
tensor([[1.2603, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0080, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.6935, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0103]])


In [18]:
import torch

arr = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#from second row select index 1 to 3
print(arr[1, 1:4]) 

#from both the rows select index 2
print(arr[0:2, 2]) 

# From both elements, slice index 1 to index 4 (not included), 
#   this will return a 2-D array:
print(arr[0:2, 1:4])

#Everything from (including) the second item to (not including) the fifth item.
print(arr[0:2, 1:4])

#select 2nd index column across all rows
print(arr[...,2])


arr = torch.tensor([
    [
        [ 
            [1111, 1112], 
            [1121, 1122] 
        ], 
        [ 
            [1211, 1212], 
            [1221, 1222] 
        ]
    ],
    [
        [ 
            [2111, 2112], 
            [2121, 2122] 
        ], 
        [ 
            [2211, 2212], 
            [2221, 2222] 
        ]
    ],
    
])
print(arr[...,1])
print(arr[0,...,1])


tensor([7, 8, 9])
tensor([3, 8])
tensor([[2, 3, 4],
        [7, 8, 9]])
tensor([[2, 3, 4],
        [7, 8, 9]])
tensor([3, 8])
tensor([[[1112, 1122],
         [1212, 1222]],

        [[2112, 2122],
         [2212, 2222]]])
tensor([[1112, 1122],
        [1212, 1222]])


In [20]:
import torch

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[4, 5], [6, 7]])

c = torch.tensor([
        [
            [111, 112, 113, 114],
            [121, 122, 123, 124],
            [131, 132, 133, 134]
        ],
        [
            [211, 212, 213, 214],
            [221, 222, 223, 224],
            [231, 232, 233, 234]
        ]
    ])

print(a.size())
print(torch.cat((a, b), dim=1))

#transpose
print("\ntranspose -->\n", torch.einsum('ji->ij', a))
print("\ntranspose -->\n", torch.einsum('ijk->ikj',c))




c = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
(c1, c2, c3) = torch.split(c, [2,1,3])
print("\nsplit -->\n", c1, c2, c3, sep="\n")


torch.Size([2, 2])
tensor([[1, 2, 4, 5],
        [3, 4, 6, 7]])

transpose -->
 tensor([[1, 3],
        [2, 4]])

transpose -->
 tensor([[[111, 121, 131],
         [112, 122, 132],
         [113, 123, 133],
         [114, 124, 134]],

        [[211, 221, 231],
         [212, 222, 232],
         [213, 223, 233],
         [214, 224, 234]]])

split -->

tensor([[1, 2],
        [3, 4]])
tensor([[5, 6]])
tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])


In [15]:
import torch

x = torch.tensor([1, 2, 3])
print(2*x**2)

x = torch.randn(2, 3)
print(x)
print(x.transpose(dim0=-1, dim1=0))

x = torch.tensor([ [1, 2], [3, 9] ])
y = torch.tensor( [ [1, 1], [1, 1] ])
print("sum of diagnol", torch.einsum('ii', x))
print("diagnol elements", torch.einsum('ii->i', x))
print("multiplication", torch.einsum('ij,jk->ik', x, y))
print("batch mul", torch.einsum('ij,jk->ik', x, y))

x = torch.tensor([ [[1, 2, 3], [4, 5, 6]], [ [7, 8, 9], [10, 11, 12] ] ])
y = torch.tensor([ [[1, 2, 3], [4, 5, 6]], [ [7, 8, 9], [10, 11, 12] ] ])


tensor([ 2,  8, 18])
tensor([[ 0.6514, -2.3178, -0.4828],
        [-0.3267, -0.3087, -0.5721]])
tensor([[ 0.6514, -0.3267],
        [-2.3178, -0.3087],
        [-0.4828, -0.5721]])
sum of diagnol tensor(10)
diagnol elements tensor([1, 9])
multiplication tensor([[ 3,  3],
        [12, 12]])
