In [ ]:
!pip3 install torch

Question 1: In this coding question, you are tasked with building a neural network with three layers using PyTorch. You need to fill in the blanks for the activation function, initialization, and the forward function to complete the implementation. The provided testing code allows them to check whether their neural network is functioning as expected.

In [74]:
import torch
import torch.nn as nn


# Step 1: Layer Dimensions
input_dim = 5  # Fill in the blank for the number of input features
hidden_dim = 10  # Fill in the blank for the number of hidden units
output_dim = 3  # Fill in the blank for the number of output units

# Step 2: Activation Function
def activation_function(x):
    return torch.relu(x)  # Fill in the blank for the activation function

# Step 3: Neural Network Architecture
class ThreeLayerNN(nn.Module):
    def __init__(self):
        super(ThreeLayerNN, self).__init__()
        self.input_layer = nn.Linear(input_dim, hidden_dim)  # Fill in the blanks for input layer dimensions
        self.hidden_layer = nn.Linear(hidden_dim , hidden_dim)  # Fill in the blanks for hidden layer dimensions
        self.output_layer = nn.Linear(hidden_dim , output_dim)  # Fill in the blanks for output layer dimensions

    def forward(self, x):
        hidden_output = activation_function(self.input_layer(x))  # Fill in the blank for the forward pass through the input layer
        hidden_output = activation_function(self.hidden_layer(hidden_output))  # Fill in the blank for the forward pass through the hidden layer
        output = self.output_layer(hidden_output)  # Fill in the blank for the forward pass through the output layer
        return output

# Step 4: Initialization and Testing
x = torch.randn(1, input_dim)
print("\ninput -->\n", x)
model = ThreeLayerNN()
print("\nmodel -->\n", model)
output = model(x)
print("\nOutput tensor -->\n", output)



input -->
 tensor([[ 0.0414, -0.2323, -1.3658,  1.9687, -1.4558]])

model -->
 ThreeLayerNN(
  (input_layer): Linear(in_features=5, out_features=10, bias=True)
  (hidden_layer): Linear(in_features=10, out_features=10, bias=True)
  (output_layer): Linear(in_features=10, out_features=3, bias=True)
)

Output tensor -->
 tensor([[-0.1165, -0.5698, -0.0750]], grad_fn=<AddmmBackward0>)


Question 2: Your task is to fill in the blanks in the "Define the Real Function" section to complete the implementation of the real function f(x). Then, fill in the blanks in the "Compute the Gradient" section to compute the gradient of the real function with respect to the input x. Lastly, obtain and print the gradient of x.

In [59]:
import torch

# Define the real function f(x) = (x^4 - 3x^3 + 2x^2 - 5x + 7) / (2x^3 + 5x^2 - x + 3)
def f1(x):
    return (x**4 - 3*x**3 + 2*x**2 - 5*x + 7)

def f2(x):
    return (2*x**3 + 5*x**2 - x + 3)

def real_function(x):
    result = f1(x)/f2(x) # Fill in the blank for the computation of the function
    return result

# Define a real number for which to compute the gradient
x = torch.tensor(1.0, requires_grad=True, dtype=torch.float32)

# Compute the real function f(x)
result = real_function(x)  # Fill in the blank to call the real function with input 'x'

# Compute the gradient of f(x) with respect to x
def gradient_f1(x):
    return (4*x**3 - 3*3*x**2 + 2*2*x - 5)
def gradient_f2(x):
    return  (2*3*x**2 + 5*2*x - 1)
def gradient_f(x):
    return (gradient_f1(x)*f2(x) - gradient_f2(x)*f1(x))/f2(x)**2

with torch.no_grad():
    gradient_result = gradient_f(x) 
    
print("result:", result)
print("Computed Gradient of x:", gradient_result)

# Obtain the gradient of x
result.backward() # Fill in the blank to compute the gradient of 'result'
gradient_x = x.grad  # Fill in the blank for the gradient of 'x'

print("Gradient of x:", gradient_x)


result: tensor(0.2222, grad_fn=<DivBackward0>)
Computed Gradient of x: tensor(-1.0370)
Gradient of x: tensor(-1.0370)


Optional Question: Below is an incomplete code for Logistic Regression in Pytorch. Your task is to fill the appropriate function calls and run the for teh specified number of epochs.

In [80]:
import torch
import torch.nn as nn
import torch.optim as optim

# Step 1: Prepare the data
# Define the number of features (input size)
input_size = 2

# Define the number of classes (output size)
output_size = 2

# Create the training dataset
X_train = torch.tensor([ [1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [5.0, 1.0] ])
y_train = torch.tensor([ 0, 1, 1, 1 ])  # Fill in the blanks for the appropriate y_train values

# Step 2: Define the logistic regression model
class LogisticRegressionModel(nn.Module):
    def __init__(self):
        super(LogisticRegressionModel, self).__init__()
        self.linear = nn.Linear(input_size, output_size)

    def forward(self, x):
        return torch.sigmoid(self.linear(x))

model = LogisticRegressionModel()

# Step 3: Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()  # Fill in the blank for the appropriate loss function
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Fill in the blank for the appropriate optimizer

# Step 4: Train the model
num_epochs = 1000
for epoch in range(num_epochs):
    # Forward pass
    outputs = model(X_train)
    loss = criterion(outputs, y_train)  # Fill in the blanks for the appropriate y_train values

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Step 5: Test the model
X_test = torch.tensor([[4.0, 3.0], [1.0, 1.0], [0.0, 0.0]], requires_grad=False)
Y_test = torch.tensor([ 1, 0, 0], requires_grad=False)
predicted = model(X_test)
predicted_class = torch.argmax(predicted, dim=1).numpy()
print("Predicted class:", predicted_class)  # Fill in the blank for the appropriate tensor to get the predicted class

Epoch [100/1000], Loss: 0.6926
Epoch [200/1000], Loss: 0.6774
Epoch [300/1000], Loss: 0.6497
Epoch [400/1000], Loss: 0.5926
Epoch [500/1000], Loss: 0.5446
Epoch [600/1000], Loss: 0.5263
Epoch [700/1000], Loss: 0.5188
Epoch [800/1000], Loss: 0.5150
Epoch [900/1000], Loss: 0.5125
Epoch [1000/1000], Loss: 0.5106
Predicted class: [1 1 0]


Optional Question: Implementing Single-Headed Attention with einsum

In this coding question, you will implement a single-headed attention function using einsum in PyTorch. The provided inspiration function demonstrates the computation of single-headed attention without using einsum. Your task is to take inspiration from the given function and write a new function that performs the same computation using einsum.

Explanation of the code without Einsum:
- Inputs:

- - query: A PyTorch tensor of shape (batch_size, sequence_length, query_dim). This tensor represents the query vectors for each token in the sequence.
- - key: A PyTorch tensor of shape (batch_size, sequence_length, key_dim). This tensor represents the key vectors for each token in the sequence.
- - value: A PyTorch tensor of shape (batch_size, sequence_length, value_dim). This tensor represents the value vectors for each token in the sequence.

- Outputs:

- - attended_values: A PyTorch tensor of shape (batch_size, sequence_length, value_dim). This tensor represents the attended values obtained by combining the value vectors with the attention weights.
- - attention_weights: A PyTorch tensor of shape (batch_size, sequence_length, sequence_length). This tensor contains the attention weights indicating the importance of each token's value in producing the attended values.

In [71]:
# Single headed attention without EinSum
import torch
import torch.nn.functional as F

def single_head_attention(query, key, value):
    # Calculate the dot product between query and key
    dot_product = torch.matmul(query, key.transpose(-2, -1))
    

    # Scale the dot product by dividing it by the square root of the dimension of the key vector
    scaled_dot_product = dot_product / (key.size(-1) ** 0.5)
    
    # Apply softmax to obtain attention weights along the last dimension (head dimension)
    attention_weights = F.softmax(scaled_dot_product, dim=-1)

    # Compute the weighted sum of value vectors
    attended_values = torch.matmul(attention_weights, value)

    return attended_values, attention_weights


# Einsum based attention goes here
def single_head_attention_with_einsum(query, key, value):
    key_t = torch.einsum('ijk->ikj', key)
    dot_product = torch.einsum('bik,bkj->bij', query, key_t)
    scaled_dot_product = dot_product / (key.size(-1) ** 0.5)
    attention_weights = F.softmax(scaled_dot_product, dim=-1)
    attended_values = torch.einsum('bik,bkj->bij', attention_weights, value)

    return attended_values, attention_weights
  

q = torch.rand(2, 3, 4)
k = torch.rand(2, 3, 4)
v = torch.rand(2, 3, 4)

(result_values, result_weights) = single_head_attention(q, k, v)
(result_einsum_values, result_einsum_weights) = single_head_attention_with_einsum(q, k, v)

print(torch.eq(result_values, result_einsum_values))
print(torch.eq(result_weights, result_einsum_weights))


tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])
